import { ToolDecorator as Tool, Widget, ExecutionContext, z } from '@nitrostack/core';
import { parseAncestryFile } from '../variant/file-parser.service.js';
import { AgentService } from './agent.service.js';

const agentService = new AgentService();

export class AgentTools {
  @Tool({
    name: 'analyze_genetic_file',
    description:
      'Upload raw genetic data from a 23andMe or AncestryDNA export file and get a personalized polygenic risk score with AI-written narrative. The agent calls the NHGRI-EBI GWAS Catalog and NCBI PubMed in a live agentic loop — it reads your real genotype (e.g. TT vs TC at rs7903146) and explains what the research actually says about your specific variants. Returns a complete PolyRiskReport plus a multi-paragraph narrative written by Claude, and a full trace of the agent\'s reasoning steps.',
    inputSchema: z.object({
      fileContent: z
        .string()
        .describe('Full text content of a 23andMe or AncestryDNA raw genetic data file (TSV format with rsid, chromosome, position, genotype columns)'),
      disease: z
        .enum(['type2_diabetes', 'coronary_artery_disease', 'age_related_macular_degeneration'])
        .describe('The disease to analyze risk for'),
      userAncestry: z
        .string()
        .optional()
        .describe('Your ancestry background (e.g. European, East Asian, South Asian, African). Improves ancestry-aware evidence filtering.'),
    }),
    examples: {
      request: {
        fileContent: '# This data file generated by 23andMe\nrsid\tchromosome\tposition\tgenotype\nrs7903146\t10\t114758349\tTC\nrs12255372\t10\t114773927\tGT',
        disease: 'type2_diabetes',
        userAncestry: 'European',
      },
      response: {
        disease: 'type2_diabetes',
        diseaseName: 'Type 2 Diabetes',
        genotypeData: true,
        riskInterpretation: { tier: 'moderate', prsScore: 0.39, percentileApprox: 61 },
        narrative: 'Your analysis shows...',
      },
    },
  })
  @Widget('risk-report')
  async analyzeGeneticFile(input: any, ctx: ExecutionContext) {
    const { fileContent, disease, userAncestry = null } = input as {
      fileContent: string;
      disease: string;
      userAncestry?: string;
    };

    ctx.logger.info('analyze_genetic_file: parsing uploaded file', { disease, hasAncestry: !!userAncestry });

    const parsedVariants = parseAncestryFile(fileContent, disease);
    ctx.logger.info('analyze_genetic_file: variants extracted', {
      total: parsedVariants.length,
      rsids: parsedVariants.map(v => v.rsid),
    });

    if (parsedVariants.length === 0) {
      throw new Error(
        `No relevant variants found for ${disease} in the uploaded file. ` +
        `Make sure this is a 23andMe or AncestryDNA raw data export and that the file contains rsIDs relevant to ${disease}.`
      );
    }

    ctx.logger.info('analyze_genetic_file: starting agentic Claude loop', { variantCount: parsedVariants.length });
    const result = await agentService.runAnalysis(parsedVariants, disease, userAncestry ?? null, ctx.logger);
    ctx.logger.info('analyze_genetic_file: agent complete', {
      disease,
      tier: result.riskInterpretation?.tier,
      agentSteps: result.agentSteps.length,
      narrativeLength: result.narrative.length,
    });

    return result;
  }
}
